stages:
  prepare:
    cmd: python -m src.prepare
    deps:
      - src/prepare.py
      - src/data_loader.py
      - data/raw/dataset.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
